export const mock_data_1 = {
  "nodes": [{
      "id": "AUD_MATCHED",
      "name": "AUD_MATCHED",
      "color": "blue"
  }, {
      "id": "BEGIN_CONVERT_CALC",
      "name": "BEGIN_CONVERT_CALC",
      "color": "blue"
  }, {
      "id": "CONVERT_END",
      "name": "CONVERT_END"
  }, {
      "id": "MSG_SEND",
      "name": "MSG_SEND",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK",
      "name": "MSG_SEND_CHECK",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK_FAILED",
      "name": "MSG_SEND_CHECK_FAILED"
  }, {
      "id": "MSG_SEND_CHECK_PASSED",
      "name": "MSG_SEND_CHECK_PASSED"
  }, {
      "id": "MSG_SEND_FAILED",
      "name": "MSG_SEND_FAILED"
  }, {
      "id": "MSG_SEND_PASSED",
      "name": "MSG_SEND_PASSED"
  }, {
      "id": "ROOT",
      "name": "ROOT",
      "color": "red"
  }],
  "edges": [{
      "source": "AUD_MATCHED",
      "target": "MSG_SEND_CHECK",
      "name": "0",
      "color": "black"
  }, {
      "source": "BEGIN_CONVERT_CALC",
      "target": "CONVERT_END",
      "name": "1",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_FAILED",
      "name": "2",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_PASSED",
      "name": "3",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_FAILED",
      "name": "4",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_PASSED",
      "name": "5",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK_PASSED",
      "target": "MSG_SEND",
      "name": "6",
      "color": "black"
  }, {
      "source": "MSG_SEND_PASSED",
      "target": "BEGIN_CONVERT_CALC",
      "name": "7",
      "color": "black"
  }, {
      "source": "ROOT",
      "target": "AUD_MATCHED",
      "name": "8",
      "color": "black"
  }]
}

export const mock_data_2 = {
  "nodes": [{
      "id": "CV_CONVERTED_C1",
      "name": "CV_CONVERTED_C1",
      "color": "blue"
  }, {
      "id": "CV_CONVERTING_C1",
      "name": "CV_CONVERTING_C1"
  }, {
      "id": "CV_CONVERT_END_C1",
      "name": "CV_CONVERT_END_C1",
      "color": "blue"
  }, {
      "id": "CV_CONVERT_TIMEOUT_C1",
      "name": "CV_CONVERT_TIMEOUT_C1"
  }, {
      "id": "CV_ROOT_C1",
      "name": "CV_ROOT_C1",
      "color": "red"
  }],
  "edges": [{
      "source": "CV_CONVERTED_C1",
      "target": "CV_CONVERT_END_C1",
      "name": "0",
      "color": "black"
  }, {
      "source": "CV_CONVERTING_C1",
      "target": "CV_CONVERTED_C1",
      "name": "1",
      "color": "black"
  }, {
      "source": "CV_CONVERTING_C1",
      "target": "CV_CONVERT_TIMEOUT_C1",
      "name": "2",
      "color": "black"
  }, {
      "source": "CV_CONVERT_END_C1",
      "target": "CV_ROOT_C1",
      "name": "3",
      "color": "black"
  }, {
      "source": "CV_CONVERT_TIMEOUT_C1",
      "target": "CV_CONVERT_END_C1",
      "name": "4",
      "color": "black"
  }, {
      "source": "CV_ROOT_C1",
      "target": "CV_CONVERTING_C1",
      "name": "5",
      "color": "black"
  }]
}

export const mock_data_3 = {
  "nodes": [{
      "id": "CC_ALL_CONVERT_END",
      "name": "CC_ALL_CONVERT_END",
      "color": "blue"
  }, {
      "id": "CC_CONVERTING",
      "name": "CC_CONVERTING",
      "color": "blue"
  }, {
      "id": "CC_ROOT",
      "name": "CC_ROOT",
      "color": "red"
  }],
  "edges": [{
      "source": "CC_ALL_CONVERT_END",
      "target": "CC_ROOT",
      "name": "0",
      "color": "black"
  }, {
      "source": "CC_CONVERTING",
      "target": "CC_ALL_CONVERT_END",
      "name": "1",
      "color": "black"
  }, {
      "source": "CC_ROOT",
      "target": "CC_CONVERTING",
      "name": "2",
      "color": "black"
  }]
}

export const mock_data_4 = {
  "nodes": [{
      "id": "AUD_MATCHED",
      "name": "AUD_MATCHED",
      "color": "blue"
  }, {
      "id": "BEGIN_CONVERT_CALC",
      "name": "BEGIN_CONVERT_CALC",
      "color": "blue"
  }, {
      "id": "CONVERT_END",
      "name": "CONVERT_END"
  }, {
      "id": "MSG_SEND",
      "name": "MSG_SEND",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK",
      "name": "MSG_SEND_CHECK",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK_FAILED",
      "name": "MSG_SEND_CHECK_FAILED"
  }, {
      "id": "MSG_SEND_CHECK_PASSED",
      "name": "MSG_SEND_CHECK_PASSED"
  }, {
      "id": "MSG_SEND_FAILED",
      "name": "MSG_SEND_FAILED"
  }, {
      "id": "MSG_SEND_PASSED",
      "name": "MSG_SEND_PASSED"
  }, {
      "id": "RECYCLE_BIN",
      "name": "RECYCLE_BIN"
  }, {
      "id": "RE_ENTER_CHECK",
      "name": "RE_ENTER_CHECK",
      "color": "blue"
  }, {
      "id": "RE_ENTER_FAILED",
      "name": "RE_ENTER_FAILED"
  }, {
      "id": "RE_ENTER_PASSED",
      "name": "RE_ENTER_PASSED"
  }, {
      "id": "ROOT",
      "name": "ROOT",
      "color": "red"
  }],
  "edges": [{
      "source": "AUD_MATCHED",
      "target": "RE_ENTER_CHECK",
      "name": "0",
      "color": "black"
  }, {
      "source": "BEGIN_CONVERT_CALC",
      "target": "CONVERT_END",
      "name": "1",
      "color": "black"
  }, {
      "source": "BEGIN_CONVERT_CALC",
      "target": "RECYCLE_BIN",
      "name": "2",
      "color": "black"
  }, {
      "source": "CONVERT_END",
      "target": "RECYCLE_BIN",
      "name": "3",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_FAILED",
      "name": "4",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_PASSED",
      "name": "5",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_FAILED",
      "name": "6",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_PASSED",
      "name": "7",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK_FAILED",
      "target": "RECYCLE_BIN",
      "name": "8",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK_PASSED",
      "target": "MSG_SEND",
      "name": "9",
      "color": "black"
  }, {
      "source": "MSG_SEND_FAILED",
      "target": "RECYCLE_BIN",
      "name": "10",
      "color": "black"
  }, {
      "source": "MSG_SEND_PASSED",
      "target": "BEGIN_CONVERT_CALC",
      "name": "11",
      "color": "black"
  }, {
      "source": "RECYCLE_BIN",
      "target": "ROOT",
      "name": "12",
      "color": "black"
  }, {
      "source": "RE_ENTER_CHECK",
      "target": "RE_ENTER_FAILED",
      "name": "13",
      "color": "black"
  }, {
      "source": "RE_ENTER_CHECK",
      "target": "RE_ENTER_PASSED",
      "name": "14",
      "color": "black"
  }, {
      "source": "RE_ENTER_FAILED",
      "target": "RECYCLE_BIN",
      "name": "15",
      "color": "black"
  }, {
      "source": "RE_ENTER_PASSED",
      "target": "MSG_SEND_CHECK",
      "name": "16",
      "color": "black"
  }, {
      "source": "ROOT",
      "target": "AUD_MATCHED",
      "name": "17",
      "color": "LightGrey"
  }]
}

export const mock_data_5 = {
  "nodes": [{
      "id": "AUD_MATCHED",
      "name": "AUD_MATCHED",
      "color": "blue"
  }, {
      "id": "BEGIN_CONVERT_CALC",
      "name": "BEGIN_CONVERT_CALC",
      "color": "blue"
  }, {
      "id": "CONVERT_END",
      "name": "CONVERT_END"
  }, {
      "id": "DELAY_BEGIN",
      "name": "DELAY_BEGIN"
  }, {
      "id": "DELAY_END",
      "name": "DELAY_END"
  }, {
      "id": "MSG_SEND",
      "name": "MSG_SEND",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK",
      "name": "MSG_SEND_CHECK",
      "color": "blue"
  }, {
      "id": "MSG_SEND_CHECK_FAILED",
      "name": "MSG_SEND_CHECK_FAILED"
  }, {
      "id": "MSG_SEND_CHECK_PASSED",
      "name": "MSG_SEND_CHECK_PASSED"
  }, {
      "id": "MSG_SEND_FAILED",
      "name": "MSG_SEND_FAILED"
  }, {
      "id": "MSG_SEND_PASSED",
      "name": "MSG_SEND_PASSED"
  }, {
      "id": "RECYCLE_BIN",
      "name": "RECYCLE_BIN"
  }, {
      "id": "RE_ENTER_CHECK",
      "name": "RE_ENTER_CHECK",
      "color": "blue"
  }, {
      "id": "RE_ENTER_FAILED",
      "name": "RE_ENTER_FAILED"
  }, {
      "id": "RE_ENTER_PASSED",
      "name": "RE_ENTER_PASSED"
  }, {
      "id": "ROOT",
      "name": "ROOT",
      "color": "red"
  }, {
      "id": "TRIGGER_A_MATCHED",
      "name": "TRIGGER_A_MATCHED"
  }, {
      "id": "TRIGGER_B_MATCHED",
      "name": "TRIGGER_B_MATCHED",
      "color": "blue"
  }],
  "edges": [{
      "source": "AUD_MATCHED",
      "target": "RECYCLE_BIN",
      "name": "0",
      "color": "black"
  }, {
      "source": "AUD_MATCHED",
      "target": "TRIGGER_A_MATCHED",
      "name": "1",
      "color": "LightGrey"
  }, {
      "source": "BEGIN_CONVERT_CALC",
      "target": "CONVERT_END",
      "name": "2",
      "color": "black"
  }, {
      "source": "BEGIN_CONVERT_CALC",
      "target": "RECYCLE_BIN",
      "name": "3",
      "color": "black"
  }, {
      "source": "CONVERT_END",
      "target": "RECYCLE_BIN",
      "name": "4",
      "color": "black"
  }, {
      "source": "DELAY_BEGIN",
      "target": "DELAY_END",
      "name": "5",
      "color": "black"
  }, {
      "source": "DELAY_END",
      "target": "MSG_SEND_CHECK",
      "name": "6",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_FAILED",
      "name": "7",
      "color": "black"
  }, {
      "source": "MSG_SEND",
      "target": "MSG_SEND_PASSED",
      "name": "8",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_FAILED",
      "name": "9",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK",
      "target": "MSG_SEND_CHECK_PASSED",
      "name": "10",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK_FAILED",
      "target": "RECYCLE_BIN",
      "name": "11",
      "color": "black"
  }, {
      "source": "MSG_SEND_CHECK_PASSED",
      "target": "MSG_SEND",
      "name": "12",
      "color": "black"
  }, {
      "source": "MSG_SEND_FAILED",
      "target": "RECYCLE_BIN",
      "name": "13",
      "color": "black"
  }, {
      "source": "MSG_SEND_PASSED",
      "target": "BEGIN_CONVERT_CALC",
      "name": "14",
      "color": "black"
  }, {
      "source": "RECYCLE_BIN",
      "target": "ROOT",
      "name": "15",
      "color": "black"
  }, {
      "source": "RE_ENTER_CHECK",
      "target": "RE_ENTER_FAILED",
      "name": "16",
      "color": "black"
  }, {
      "source": "RE_ENTER_CHECK",
      "target": "RE_ENTER_PASSED",
      "name": "17",
      "color": "black"
  }, {
      "source": "RE_ENTER_FAILED",
      "target": "RECYCLE_BIN",
      "name": "18",
      "color": "black"
  }, {
      "source": "RE_ENTER_PASSED",
      "target": "DELAY_BEGIN",
      "name": "19",
      "color": "black"
  }, {
      "source": "ROOT",
      "target": "AUD_MATCHED",
      "name": "20",
      "color": "black"
  }, {
      "source": "TRIGGER_A_MATCHED",
      "target": "TRIGGER_B_MATCHED",
      "name": "21",
      "color": "LightGrey"
  }, {
      "source": "TRIGGER_B_MATCHED",
      "target": "MSG_SEND",
      "name": "22",
      "color": "black"
  }, {
      "source": "TRIGGER_B_MATCHED",
      "target": "RE_ENTER_CHECK",
      "name": "23",
      "color": "black"
  }]
}

export const mock_data_6 = {
  "nodes": [{
      "id": "AUD_MATCHED",
      "name": "AUD_MATCHED",
      "color": "blue"
  }, {
      "id": "RECYCLE_BIN",
      "name": "RECYCLE_BIN"
  }, {
      "id": "ROOT",
      "name": "ROOT",
      "color": "red"
  }, {
      "id": "SU_DELAY_BEGIN_S100",
      "name": "SU_DELAY_BEGIN_S100",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S101",
      "name": "SU_DELAY_BEGIN_S101",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S102",
      "name": "SU_DELAY_BEGIN_S102",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S103",
      "name": "SU_DELAY_BEGIN_S103",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S104",
      "name": "SU_DELAY_BEGIN_S104",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S105",
      "name": "SU_DELAY_BEGIN_S105",
      "color": "blue"
  }, {
      "id": "SU_DELAY_BEGIN_S106",
      "name": "SU_DELAY_BEGIN_S106",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S100",
      "name": "SU_DELAY_END_S100",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S101",
      "name": "SU_DELAY_END_S101",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S102",
      "name": "SU_DELAY_END_S102",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S103",
      "name": "SU_DELAY_END_S103",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S104",
      "name": "SU_DELAY_END_S104",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S105",
      "name": "SU_DELAY_END_S105",
      "color": "blue"
  }, {
      "id": "SU_DELAY_END_S106",
      "name": "SU_DELAY_END_S106",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S100",
      "name": "SU_MATCHED_S100",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S101",
      "name": "SU_MATCHED_S101",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S102",
      "name": "SU_MATCHED_S102",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S103",
      "name": "SU_MATCHED_S103",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S104",
      "name": "SU_MATCHED_S104",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S105",
      "name": "SU_MATCHED_S105",
      "color": "blue"
  }, {
      "id": "SU_MATCHED_S106",
      "name": "SU_MATCHED_S106",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S100",
      "name": "SU_MSG_SEND_CHECK_FAILED_S100"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S101",
      "name": "SU_MSG_SEND_CHECK_FAILED_S101"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S102",
      "name": "SU_MSG_SEND_CHECK_FAILED_S102"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S103",
      "name": "SU_MSG_SEND_CHECK_FAILED_S103"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S104",
      "name": "SU_MSG_SEND_CHECK_FAILED_S104"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S105",
      "name": "SU_MSG_SEND_CHECK_FAILED_S105"
  }, {
      "id": "SU_MSG_SEND_CHECK_FAILED_S106",
      "name": "SU_MSG_SEND_CHECK_FAILED_S106"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S100",
      "name": "SU_MSG_SEND_CHECK_PASSED_S100"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S101",
      "name": "SU_MSG_SEND_CHECK_PASSED_S101"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S102",
      "name": "SU_MSG_SEND_CHECK_PASSED_S102"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S103",
      "name": "SU_MSG_SEND_CHECK_PASSED_S103"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S104",
      "name": "SU_MSG_SEND_CHECK_PASSED_S104"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S105",
      "name": "SU_MSG_SEND_CHECK_PASSED_S105"
  }, {
      "id": "SU_MSG_SEND_CHECK_PASSED_S106",
      "name": "SU_MSG_SEND_CHECK_PASSED_S106"
  }, {
      "id": "SU_MSG_SEND_CHECK_S100",
      "name": "SU_MSG_SEND_CHECK_S100",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S101",
      "name": "SU_MSG_SEND_CHECK_S101",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S102",
      "name": "SU_MSG_SEND_CHECK_S102",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S103",
      "name": "SU_MSG_SEND_CHECK_S103",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S104",
      "name": "SU_MSG_SEND_CHECK_S104",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S105",
      "name": "SU_MSG_SEND_CHECK_S105",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_CHECK_S106",
      "name": "SU_MSG_SEND_CHECK_S106",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_FAILED_S100",
      "name": "SU_MSG_SEND_FAILED_S100"
  }, {
      "id": "SU_MSG_SEND_FAILED_S101",
      "name": "SU_MSG_SEND_FAILED_S101"
  }, {
      "id": "SU_MSG_SEND_FAILED_S102",
      "name": "SU_MSG_SEND_FAILED_S102"
  }, {
      "id": "SU_MSG_SEND_FAILED_S103",
      "name": "SU_MSG_SEND_FAILED_S103"
  }, {
      "id": "SU_MSG_SEND_FAILED_S104",
      "name": "SU_MSG_SEND_FAILED_S104"
  }, {
      "id": "SU_MSG_SEND_FAILED_S105",
      "name": "SU_MSG_SEND_FAILED_S105"
  }, {
      "id": "SU_MSG_SEND_FAILED_S106",
      "name": "SU_MSG_SEND_FAILED_S106"
  }, {
      "id": "SU_MSG_SEND_PASSED_S100",
      "name": "SU_MSG_SEND_PASSED_S100"
  }, {
      "id": "SU_MSG_SEND_PASSED_S101",
      "name": "SU_MSG_SEND_PASSED_S101"
  }, {
      "id": "SU_MSG_SEND_PASSED_S102",
      "name": "SU_MSG_SEND_PASSED_S102"
  }, {
      "id": "SU_MSG_SEND_PASSED_S103",
      "name": "SU_MSG_SEND_PASSED_S103"
  }, {
      "id": "SU_MSG_SEND_PASSED_S104",
      "name": "SU_MSG_SEND_PASSED_S104"
  }, {
      "id": "SU_MSG_SEND_PASSED_S105",
      "name": "SU_MSG_SEND_PASSED_S105"
  }, {
      "id": "SU_MSG_SEND_PASSED_S106",
      "name": "SU_MSG_SEND_PASSED_S106"
  }, {
      "id": "SU_MSG_SEND_S100",
      "name": "SU_MSG_SEND_S100",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S101",
      "name": "SU_MSG_SEND_S101",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S102",
      "name": "SU_MSG_SEND_S102",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S103",
      "name": "SU_MSG_SEND_S103",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S104",
      "name": "SU_MSG_SEND_S104",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S105",
      "name": "SU_MSG_SEND_S105",
      "color": "blue"
  }, {
      "id": "SU_MSG_SEND_S106",
      "name": "SU_MSG_SEND_S106",
      "color": "blue"
  }, {
      "id": "SU_RECYCLE_BIN",
      "name": "SU_RECYCLE_BIN"
  }],
  "edges": [{
      "source": "AUD_MATCHED",
      "target": "SU_MATCHED_S100",
      "name": "0",
      "color": "LightGrey"
  }, {
      "source": "AUD_MATCHED",
      "target": "SU_MATCHED_S101",
      "name": "1",
      "color": "LightGrey"
  }, {
      "source": "RECYCLE_BIN",
      "target": "ROOT",
      "name": "2",
      "color": "black"
  }, {
      "source": "ROOT",
      "target": "AUD_MATCHED",
      "name": "3",
      "color": "LightGrey"
  }, {
      "source": "SU_DELAY_BEGIN_S100",
      "target": "SU_DELAY_END_S100",
      "name": "4",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S100",
      "target": "SU_RECYCLE_BIN",
      "name": "5",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S101",
      "target": "SU_DELAY_END_S101",
      "name": "6",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S101",
      "target": "SU_RECYCLE_BIN",
      "name": "7",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S102",
      "target": "SU_DELAY_END_S102",
      "name": "8",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S102",
      "target": "SU_RECYCLE_BIN",
      "name": "9",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S103",
      "target": "SU_DELAY_END_S103",
      "name": "10",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S103",
      "target": "SU_RECYCLE_BIN",
      "name": "11",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S104",
      "target": "SU_DELAY_END_S104",
      "name": "12",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "13",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S105",
      "target": "SU_DELAY_END_S105",
      "name": "14",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "15",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S106",
      "target": "SU_DELAY_END_S106",
      "name": "16",
      "color": "black"
  }, {
      "source": "SU_DELAY_BEGIN_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "17",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S100",
      "target": "SU_MSG_SEND_CHECK_S100",
      "name": "18",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S101",
      "target": "SU_MSG_SEND_CHECK_S101",
      "name": "19",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S102",
      "target": "SU_MSG_SEND_CHECK_S102",
      "name": "20",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S103",
      "target": "SU_MSG_SEND_CHECK_S103",
      "name": "21",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S104",
      "target": "SU_MSG_SEND_CHECK_S104",
      "name": "22",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S105",
      "target": "SU_MSG_SEND_CHECK_S105",
      "name": "23",
      "color": "black"
  }, {
      "source": "SU_DELAY_END_S106",
      "target": "SU_MSG_SEND_CHECK_S106",
      "name": "24",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S100",
      "target": "SU_DELAY_BEGIN_S100",
      "name": "25",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S101",
      "target": "SU_DELAY_BEGIN_S101",
      "name": "26",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S102",
      "target": "SU_DELAY_BEGIN_S102",
      "name": "27",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S103",
      "target": "SU_DELAY_BEGIN_S103",
      "name": "28",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S104",
      "target": "SU_DELAY_BEGIN_S104",
      "name": "29",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S105",
      "target": "SU_DELAY_BEGIN_S105",
      "name": "30",
      "color": "black"
  }, {
      "source": "SU_MATCHED_S106",
      "target": "SU_DELAY_BEGIN_S106",
      "name": "31",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S100",
      "target": "SU_RECYCLE_BIN",
      "name": "32",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S101",
      "target": "SU_RECYCLE_BIN",
      "name": "33",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S102",
      "target": "SU_RECYCLE_BIN",
      "name": "34",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S103",
      "target": "SU_RECYCLE_BIN",
      "name": "35",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "36",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "37",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_FAILED_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "38",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S100",
      "target": "SU_MSG_SEND_S100",
      "name": "39",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S101",
      "target": "SU_MSG_SEND_S101",
      "name": "40",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S102",
      "target": "SU_MSG_SEND_S102",
      "name": "41",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S103",
      "target": "SU_MSG_SEND_S103",
      "name": "42",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S104",
      "target": "SU_MSG_SEND_S104",
      "name": "43",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S105",
      "target": "SU_MSG_SEND_S105",
      "name": "44",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_PASSED_S106",
      "target": "SU_MSG_SEND_S106",
      "name": "45",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S100",
      "target": "SU_MSG_SEND_CHECK_FAILED_S100",
      "name": "46",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S100",
      "target": "SU_MSG_SEND_CHECK_PASSED_S100",
      "name": "47",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S100",
      "target": "SU_RECYCLE_BIN",
      "name": "48",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S101",
      "target": "SU_MSG_SEND_CHECK_FAILED_S101",
      "name": "49",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S101",
      "target": "SU_MSG_SEND_CHECK_PASSED_S101",
      "name": "50",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S101",
      "target": "SU_RECYCLE_BIN",
      "name": "51",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S102",
      "target": "SU_MSG_SEND_CHECK_FAILED_S102",
      "name": "52",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S102",
      "target": "SU_MSG_SEND_CHECK_PASSED_S102",
      "name": "53",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S102",
      "target": "SU_RECYCLE_BIN",
      "name": "54",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S103",
      "target": "SU_MSG_SEND_CHECK_FAILED_S103",
      "name": "55",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S103",
      "target": "SU_MSG_SEND_CHECK_PASSED_S103",
      "name": "56",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S103",
      "target": "SU_RECYCLE_BIN",
      "name": "57",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S104",
      "target": "SU_MSG_SEND_CHECK_FAILED_S104",
      "name": "58",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S104",
      "target": "SU_MSG_SEND_CHECK_PASSED_S104",
      "name": "59",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "60",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S105",
      "target": "SU_MSG_SEND_CHECK_FAILED_S105",
      "name": "61",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S105",
      "target": "SU_MSG_SEND_CHECK_PASSED_S105",
      "name": "62",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "63",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S106",
      "target": "SU_MSG_SEND_CHECK_FAILED_S106",
      "name": "64",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S106",
      "target": "SU_MSG_SEND_CHECK_PASSED_S106",
      "name": "65",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_CHECK_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "66",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S100",
      "target": "SU_RECYCLE_BIN",
      "name": "67",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S101",
      "target": "SU_RECYCLE_BIN",
      "name": "68",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S102",
      "target": "SU_RECYCLE_BIN",
      "name": "69",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S103",
      "target": "SU_RECYCLE_BIN",
      "name": "70",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "71",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "72",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_FAILED_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "73",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_PASSED_S100",
      "target": "SU_MATCHED_S102",
      "name": "74",
      "color": "LightGrey"
  }, {
      "source": "SU_MSG_SEND_PASSED_S100",
      "target": "SU_MATCHED_S103",
      "name": "75",
      "color": "LightGrey"
  }, {
      "source": "SU_MSG_SEND_PASSED_S101",
      "target": "SU_MATCHED_S106",
      "name": "76",
      "color": "LightGrey"
  }, {
      "source": "SU_MSG_SEND_PASSED_S102",
      "target": "SU_MATCHED_S105",
      "name": "77",
      "color": "LightGrey"
  }, {
      "source": "SU_MSG_SEND_PASSED_S103",
      "target": "SU_MATCHED_S104",
      "name": "78",
      "color": "LightGrey"
  }, {
      "source": "SU_MSG_SEND_PASSED_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "79",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_PASSED_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "80",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_PASSED_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "81",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S100",
      "target": "SU_MSG_SEND_FAILED_S100",
      "name": "82",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S100",
      "target": "SU_MSG_SEND_PASSED_S100",
      "name": "83",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S100",
      "target": "SU_RECYCLE_BIN",
      "name": "84",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S101",
      "target": "SU_MSG_SEND_FAILED_S101",
      "name": "85",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S101",
      "target": "SU_MSG_SEND_PASSED_S101",
      "name": "86",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S101",
      "target": "SU_RECYCLE_BIN",
      "name": "87",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S102",
      "target": "SU_MSG_SEND_FAILED_S102",
      "name": "88",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S102",
      "target": "SU_MSG_SEND_PASSED_S102",
      "name": "89",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S102",
      "target": "SU_RECYCLE_BIN",
      "name": "90",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S103",
      "target": "SU_MSG_SEND_FAILED_S103",
      "name": "91",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S103",
      "target": "SU_MSG_SEND_PASSED_S103",
      "name": "92",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S103",
      "target": "SU_RECYCLE_BIN",
      "name": "93",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S104",
      "target": "SU_MSG_SEND_FAILED_S104",
      "name": "94",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S104",
      "target": "SU_MSG_SEND_PASSED_S104",
      "name": "95",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S104",
      "target": "SU_RECYCLE_BIN",
      "name": "96",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S105",
      "target": "SU_MSG_SEND_FAILED_S105",
      "name": "97",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S105",
      "target": "SU_MSG_SEND_PASSED_S105",
      "name": "98",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S105",
      "target": "SU_RECYCLE_BIN",
      "name": "99",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S106",
      "target": "SU_MSG_SEND_FAILED_S106",
      "name": "100",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S106",
      "target": "SU_MSG_SEND_PASSED_S106",
      "name": "101",
      "color": "black"
  }, {
      "source": "SU_MSG_SEND_S106",
      "target": "SU_RECYCLE_BIN",
      "name": "102",
      "color": "black"
  }, {
      "source": "SU_RECYCLE_BIN",
      "target": "RECYCLE_BIN",
      "name": "103",
      "color": "black"
  }]
}
